spring.application.name=backend
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/document_dashboard?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=200MB

# Custom property for upload directory
file.upload-dir=uploads
